# Esercitazione 4

## Istruzioni
Valgono le stesse istruzioni delle esercitazioni precedenti. 

Scrivi il programma Python nella cella sotto il testo dell'esercizio (o creane una nuova). Stampa sempre a video il risultato finale per verificare la correttezza dell'esercizio.  Talvolta richiamiamo alcuni concetti importanti in una cella di codice sotto il testo dell'esercizio, prova a eseguirla ed eventualmente modificarla per assicurarti di aver capito il necessario.

**Nota.** Alcuni esercizi potrebbero richiedere una semplice risposta a delle domande. In questo caso potete scrivere la soluzione in una cella di tipo "Markdown".  


## Consegna
Valgono le regole delle esercitazioni precedenti.

E' obbligatorio **consegnare la soluzione di tutti gli esercizi** (tranne quelli marcati come opzionali) **entro l'inizio della lezione successiva** (in questo caso entro Lunedi' prossimo), nell'apposito assignment su iCorsi.  Per consegnare:
- eseguire l'intero notebook partendo da zero (`Kernel -> Restart & Run All`), e controllare che le soluzioni siano quelle attese;
- esportare il notebook in formato html (`File -> Download as...`) e consegnare il file risultante.

Nel caso non abbiate potuto completare uno o piu' esercizi, descrivete il problema incontrato e **consegnate comunque il file con il resto delle soluzioni**.

## Esercizio 1 (variabili categoriche)

Scaricare il dataset [profili.csv](https://github.com/rudeboybert/JSE_OkCupid/blob/master/profiles.csv.zip) e importarlo eseguendo i comandi nella cella sotto (assicuratevi di aver salvato il file profili.csv nella stessa cartella del file .ipynb su cui state lavorando, oppure specificate il percorso in cui si trova il file profili.csv). Provate a capire come è fatto il dataset (es., da quanti elementi è composto, quali sono gli attributi, quali valori possono assumere le variabili, etc.). Informazioni sul dataset si possono trovare [QUI](https://nbviewer.jupyter.org/github/alessandro-giusti/profiles_analysis/blob/master/profiles.ipynb)

In [1]:
# Carichiamo il dataset e visualizziamo qualcosa
import pandas as pd
import numpy as np

df = pd.read_csv("profiles.csv")

print(df.columns,"\n\n -------------------------------------")  # Visualizzo le variabili (nomi delle colonne) del dataframe
print(df.head(2),"\n\n -------------------------------------")    # Visualizzo primi 2 elementi del dataframe

Index(['age', 'body_type', 'diet', 'drinks', 'drugs', 'education', 'essay0',
       'essay1', 'essay2', 'essay3', 'essay4', 'essay5', 'essay6', 'essay7',
       'essay8', 'essay9', 'ethnicity', 'height', 'income', 'job',
       'last_online', 'location', 'offspring', 'orientation', 'pets',
       'religion', 'sex', 'sign', 'smokes', 'speaks', 'status'],
      dtype='object') 

 -------------------------------------
   age       body_type               diet    drinks      drugs  \
0   22  a little extra  strictly anything  socially      never   
1   35         average       mostly other     often  sometimes   

                       education  \
0  working on college/university   
1          working on space camp   

                                              essay0  \
0  about me:<br />\n<br />\ni would love to think...   
1  i am a chef: this is what that means.<br />\n1...   

                                              essay1  \
0  currently working as an international agent f

### 1.1 
Si consideri la variabile "smokes". Quali possibili valori assume questa variabile? Hint: trasforma un array in un set per eliminare i duplicati

In [2]:
# Hints

# Per trasformare una colonna da un dataframe in un numpy array
print(f"Valori della variabile 'diet' per ogni osservazione:\n {df['diet'].values} \n")

# Per visualizzare i diversi valori assunti da un array
print(f"Diversi valori assunti dalla variabile 'diet': {set(df['diet'].values)}")

Valori della variabile 'diet' per ogni osservazione:
 ['strictly anything' 'mostly other' 'anything' ... 'mostly anything'
 'mostly anything' nan] 

Diversi valori assunti dalla variabile 'diet': {'anything', nan, 'mostly anything', 'strictly other', 'strictly anything', 'strictly kosher', 'mostly vegan', 'mostly halal', 'halal', 'vegan', 'strictly vegetarian', 'kosher', 'vegetarian', 'mostly vegetarian', 'other', 'strictly vegan', 'mostly kosher', 'mostly other', 'strictly halal'}


In [3]:
# Solution

print(f"Valore della variabile 'smokes' per ogni osservazione:\n {df['smokes'].values} \n")

# Per visualizzare i diversi valori assunti da un array
print(f"Valori assunti dalla variabile 'smokes': {set(df['smokes'].values)}")

Valore della variabile 'smokes' per ogni osservazione:
 ['sometimes' 'no' 'no' ... 'no' 'trying to quit' 'sometimes'] 

Valori assunti dalla variabile 'smokes': {nan, 'when drinking', 'yes', 'sometimes', 'no', 'trying to quit'}


Notate che la variabile "smokes" assume spesso il valore nan (il campo non è stato compilato dall'utente). Eseguiamo la cella sotto (provate a capire come funziona) per creare un nuovo dataset dove eliminiamo le righe (nel nostro caso gli utenti) del dataframe dove il campo "smokes" non è stato compilato. Nel seguito lavoreremo sul nuovo dataset. 

In [4]:
dfNew = df.dropna(subset=['smokes'])
dfNew[['sex', 'smokes']].values # Visualizzo array con sesso dell'utente e la variabile "smokes"

array([['m', 'sometimes'],
       ['m', 'no'],
       ['m', 'no'],
       ...,
       ['m', 'no'],
       ['m', 'trying to quit'],
       ['m', 'sometimes']], dtype=object)

### 1.2 

Raggruppate la variabile "smokes" nei seguenti 2 gruppi: 
- Primo gruppo di nome NoSmoker (questo gruppo identifica i non fumatori: tutti quelli che hanno idicato {no} nel campo "smokes") 
- Secondo gruppo di nome Smoker (questo gruppo identifica per noi tutti i fumatori: quelli che NON hanno indicato 'no' nel campo 'smokes')

Si costruisca la tabella di contingenza per la coppia di variabili "sex" e "smokes" (usando i gruppi definiti sopra).  

Hint1: Non dovete usare particolari comandi Python per calcolare la tabella di contingenza. Ricordatevi come è definita e provate a costruirla voi.  
Hint2: Nella cella sotto trovate un modo veloce per visualizzare una tabella utilizzando il pacchetto Plotly. Maggiori dettagli [QUI](https://plot.ly/python/table/). Oppure visualizzate un dataframe in pandas come visto a lezione. 

In [5]:
# Hint (plot Table)
import plotly.offline as py
import plotly.graph_objs as go
py.init_notebook_mode(connected=True)

# Plotto Tabella con plotly
valori = [ ["Benz", "Diesel"], [9, 0], [109, 9], [65, 11]] # Ogni elemento della lista è una colonna della tabella

trace = go.Table(
                header = dict(values = ["Trazione \t \n Alimentazione", "4x4", "fwd", "bwd"]),
                cells = dict(values = valori) )
py.iplot([trace])

# Plotto Tabella come dataframe
valori = [[9, 109, 65], [0, 9, 11]]
t = pd.DataFrame(valori, index = ["Benz", "Diesel"], columns = ["4x4", "fwd", "bwd"])
t

4x4  fwd  bwd
Benz      9  109   65
Diesel    0    9   11

In [6]:
# Hint2: Potrebbe servirvi per verificare, senza usare un ciclo for, se gli elementi di un array assumono valori contenuti in una lista 
import numpy as np

mioArray = np.array([1,2,3,4,5,6,7])
lista = [2,5,9]
print(np.isin(mioArray,lista))

[False  True False False  True False False]


In [7]:
# Solution

arraySex  =  dfNew['sex'].values
arraySmokeV = dfNew['smokes'].values
m = np.shape(arraySmokeV)[0]
arraySmoke = np.full(m,"",dtype = object)

for i in range(m):
    if arraySmokeV[i] == 'no':
        arraySmoke[i] = "NoSMOKER"
    else:
        arraySmoke[i] = "SMOKER"
    

groupSex = np.unique(arraySex)
groupSmoke = np.unique(arraySmoke)

matrice = np.zeros( (len(groupSex), len(groupSmoke)) ) # Creo tabella di contingenza

for sex in range(len(groupSex)):
    for smoke in range(len(groupSmoke)):
        matrice[sex,smoke] = np.sum( (arraySex == groupSex[sex]) & (arraySmoke == groupSmoke[smoke]) )

print('Tabella di contingenza')        
pd.DataFrame(matrice, index = groupSex, columns = groupSmoke)         

Tabella di contingenza


NoSMOKER  SMOKER
f   18261.0  3804.0
m   25635.0  6734.0

### 1.3

Rappresentate graficamente i risultati della tabell di contingenza tramite un bar plot

In [30]:
# Solution
# rappresentazione tramite bar plot
trace1 = go.Bar(
    x=groupSex,
    y=matrice[:,0],
    name=groupSmoke[0]
)
trace2 = go.Bar(
    x=groupSex,
    y=matrice[:,1],
    name=groupSmoke[1]
)

data = [trace1, trace2]
layout = go.Layout(
    barmode='group',
    xaxis=dict(title="Sesso"),
    yaxis=dict(title="numero di utenti")
)

fig = go.Figure(data=data, layout=layout)
py.iplot(fig, filename='grouped-bar')

### 1.4 

Calcolare le frequenze assolute marginali per riga e per colonna. Che informazione ricaviamo dalle frequenze assolute marginali? 

In [9]:
# Solution
print(f"frequenze assolute marginali per riga: {np.sum(matrice, axis = 1)}")
print(f"frequenze assolute marginali per colnna: {np.sum(matrice, axis = 0)}")

print("Le frequenze assolute marginali per riga rappresentano il numero totale di utenti femmine e maschi")
print("Le frequenze assolute marginali per riga rappresentano il numero totale di utenti fumatori e non fumatori")

frequenze assolute marginali per riga: [22065. 32369.]
frequenze assolute marginali per colnna: [43896. 10538.]
Le frequenze assolute marginali per riga rappresentano il numero totale di utenti femmine e maschi
Le frequenze assolute marginali per riga rappresentano il numero totale di utenti fumatori e non fumatori


### 1.5 

Calcolare le frequenze relative marginali per riga e per colonna. Che informazione ricaviamo dalle frequenze relative marginali? 

In [10]:
# Solution
print(f"frequenze relative marginali per riga: {np.sum(matrice, axis = 1)/m}")
print(f"frequenze relative marginali per colnna: {np.sum(matrice, axis = 0)/m}")

print("Le frequenze relative marginali per riga rappresentano la frazione di utenti femmine e maschi")
print("Le frequenze relative marginali per riga rappresentano la frazione di utenti fumatori e non fumatori")


frequenze relative marginali per riga: [0.40535327 0.59464673]
frequenze relative marginali per colnna: [0.80640776 0.19359224]
Le frequenze relative marginali per riga rappresentano la frazione di utenti femmine e maschi
Le frequenze relative marginali per riga rappresentano la frazione di utenti fumatori e non fumatori


### 1.6

Calcolare le frequenze relative condizionate per riga. Che informazioni ricaviamo da queste frequenze?

In [11]:
# Solution
matriceCondRiga = np.zeros(np.shape(matrice))

matriceCondRiga[0,:] = matrice[0,:] / np.sum(matrice, axis = 1)[0]
matriceCondRiga[1,:] = matrice[1,:] / np.sum(matrice, axis = 1)[1]
print(matriceCondRiga)

print("Nella prima riga vediamo la frazione di non fumatori e fumatori tra gli utenti donne")
print("Nella seconda riga vediamo la frazione  di non fumatori e fumatori tra gli utenti uomini")

[[0.82760027 0.17239973]
 [0.79196144 0.20803856]]
Nella prima riga vediamo la frazione di non fumatori e fumatori tra gli utenti donne
Nella seconda riga vediamo la frazione  di non fumatori e fumatori tra gli utenti uomini


### 1.7

Calcolare le frequenze relative condizionate per colonna. Che informazioni ricaviamo da queste frequenze?

In [12]:
# Solution
matriceCondColonna = np.zeros(np.shape(matrice))

matriceCondColonna[:,0] = matrice[:,0] / np.sum(matrice, axis = 0)[0]
matriceCondColonna[:,1] = matrice[:,1] / np.sum(matrice, axis = 0)[1]
print(matriceCondColonna)

print("Nella prima coloonna osserviamo la frazione di donne e uomini tra gli utenti NON fumatori")
print("Nella seconda coloonna osserviamo la frazione di donne e uomini tra gli utenti fumatori")

[[0.41600601 0.36097931]
 [0.58399399 0.63902069]]
Nella prima coloonna osserviamo la frazione di donne e uomini tra gli utenti NON fumatori
Nella seconda coloonna osserviamo la frazione di donne e uomini tra gli utenti fumatori


### 1.8 (opzionale)
Rispondete alle seguenti domande. 

In [13]:
print(f"Tra i maschi, quale percentuale si dichiara non fumatore? \n")
print(f"Tra i maschi, quale percentuale si dichiara fumatore? \n")

print(f"Tra le femmine, quale percentuale si dichiara non fumatore? \n")
print(f"Tra le femmine, quale percentuale si dichiara fumatore? \n")

print(f"Tra gli utenti non fumatori, quale percentuale è maschio? \n")
print(f"Tra gli utenti non fumatori, quale percentuale è femmina? \n")

print(f"Tra gli utenti fumatori, quale percentuale è maschio? \n")
print(f"Tra gli utenti fumatori, quale percentuale è femmina? \n")

Tra i maschi, quale percentuale si dichiara non fumatore? 

Tra i maschi, quale percentuale si dichiara fumatore? 

Tra le femmine, quale percentuale si dichiara non fumatore? 

Tra le femmine, quale percentuale si dichiara fumatore? 

Tra gli utenti non fumatori, quale percentuale è maschio? 

Tra gli utenti non fumatori, quale percentuale è femmina? 

Tra gli utenti fumatori, quale percentuale è maschio? 

Tra gli utenti fumatori, quale percentuale è femmina? 



In [14]:
# Solution

print(f"Tra i maschi, quale percentuale si dichiara non fumatore? {matriceCondRiga[1,0]}\n")
print(f"Tra i maschi, quale percentuale si dichiara fumatore? {matriceCondRiga[1,1]} \n")

print(f"Tra le femmine, quale percentuale si dichiara non fumatore? {matriceCondRiga[0,0]}\n")
print(f"Tra le femmine, quale percentuale si dichiara fumatore? {matriceCondRiga[0,1]} \n")

print(f"Tra i non fumatori, quale percentuale è maschio? {matriceCondColonna[1,0]}\n")
print(f"Tra i non fumatori, quale percentuale è femmina? {matriceCondColonna[0,0]}\n")

print(f"Tra i fumatori, quale percentuale è maschio? {matriceCondColonna[1,1]}\n")
print(f"Tra i fumatori, quale percentuale è femmina? {matriceCondColonna[0,1]}\n")

Tra i maschi, quale percentuale si dichiara non fumatore? 0.791961444592048

Tra i maschi, quale percentuale si dichiara fumatore? 0.20803855540795205 

Tra le femmine, quale percentuale si dichiara non fumatore? 0.8276002719238613

Tra le femmine, quale percentuale si dichiara fumatore? 0.17239972807613868 

Tra i non fumatori, quale percentuale è maschio? 0.5839939857845817

Tra i non fumatori, quale percentuale è femmina? 0.4160060142154183

Tra i fumatori, quale percentuale è maschio? 0.6390206870373885

Tra i fumatori, quale percentuale è femmina? 0.3609793129626115



### 1.9 (opzionale)
Ripetere i punti precedenti considerando un'altra coppia di variabili categoriche. Potete raggruppare le variabili come sopra in modo da raggruppare una variabile categorica in pochi gruppi (es., per il campo "diet" potete formare tre gruppi: "Onnivori", "Vegetariani e Vegani", "Altro") oppure potete dividere una variabile numerica (es. età) in diversi gruppi (es. "giovani" con età < 25 anni, "meno giovani" con età tra 25 e 40 anni, "senior" con età superiore a 40 anni).

## Esercizio 2

Si consideri il dataset ``profili.csv`` considerato nell'esercizio precedente, escludendo gli studenti. Si consideri la variabile numerica ``età`` e la variabile categorica ``Lavoratore`` che assume valori "YES" (se l'utente dichiara di avere un lavoro), "NO" (se l'utente dichiara di non avere un lavoro). La cella sotto esclude dal dataset tutti gli utenti che sono studenti o che non dichiarano il proprio lavoro e raggruppa gli utenti in base alla variabile ``Lavoratore`` definita sopra. L'array finale è ``jobArray``. Opzionale: Provate a capire i comandi eseguiti nella cella sotto.  

In [15]:
dfNew = df.dropna(subset = ['job'])

m = len(dfNew['job'].values)
jobArray = np.full(m, "", dtype = object)

for i in range(m):
    if dfNew['job'].values[i] == 'unemployed':
        jobArray[i] = 'NO' 
    else:
        jobArray[i] = 'YES' 

### 2.1 
Disegnare un grouped boxplot che confronti la distribuzione dell'età per le varie sottoclassi identificate dalla variabile ``Lavoratore``.  

In [16]:
# Solution

ageArray = dfNew['age'].values
box1 = go.Box(y =  ageArray[jobArray == 'YES'],
              name = "Occupati"
             )

box2 = go.Box(y =  ageArray[jobArray == 'NO'],
              name = "Disoccupati"
             ) 
 

layout = go.Layout(title = 'Grouped Box Plot for online dating profiles: Lavoratore (YES/NO) vs age', 
                   yaxis = dict(title = 'age'))

groupBox = go.Figure(data = [box1,  box2], layout = layout)

py.iplot(groupBox)

### 2.2 
Simile al punto 2.1. Disegnare due istogrammi sovrapposti per confrontare la distribuzione dell'età per le varie sottoclassi identificate dalla variabile ``Lavoratore``. Perchè uno degli istogrammi non è ben visibile?

In [17]:
# Solution

hist1 = go.Histogram(x =  ageArray[jobArray == 'YES'],
              name = "Occupati"
             )

hist2 = go.Histogram(x =  ageArray[jobArray == 'NO'],
              name = "Disoccupati"
             ) 
 

layout = go.Layout(title = "Distribuzione delle età' degli utenti", xaxis = dict(title ='età'), yaxis = dict(title = 'Numero di utenti') )

groupBox = go.Figure(data = [hist1,  hist2], layout = layout)

py.iplot(groupBox)

### 2.3 (opzionale)

L'istogramma generato al punto precedente che rappresenta la distribuzione delle età degli utenti disoccupati non è ben visibile nella stessa figura dell'istogramma che rappresenta la distribuzione delle età degli utenti lavoratori poichè il numero di utenti disoccupati è molto piu' basso rispetto ai lavoratori. Di conseguenza, anche le barre dell'istogramma sono molto piu' basse rispetto alle barre dell'istogramma caratterizzante gli utenti lavoratori. In questo caso, sarebbe meglio "normalizzare" gli istogrammi, dove l'altezza delle barre non è la frequenza assoluta (numero di utenti in un intervallo di età), ma la frequenta relativa (frazione di utenti in un intervallo di età). La cella sotto mostra come generare un istogramma normalizzato (basta impostare l'attributo ``histnorm`` uguale a ``probability'`` quando si creare l'oggetto della classe ``go.Histogram``).  

In [18]:
#Hint
x = np.random.randn(1000)

trace = go.Histogram(x = x, histnorm = 'probability', marker = dict(color = 'rgb(255,0,0)'))
layout = go.Layout(title = 'Esempio di istogramma normalizzato', xaxis = dict(title = 'x'), yaxis = dict(title = 'frequenze relative'))
fig = go.Figure([trace], layout)
py.iplot(fig)

Generate adesso gli istogrammi normalizzati dell'età dei disoccupati e dei lavoratori.

In [19]:
# Solution

hist1 = go.Histogram(x =  ageArray[jobArray == 'YES'],
              name = "Occupato",
             histnorm = 'probability',
             marker = dict(color = 'rgb(255,0,0)')         
             )

hist2 = go.Histogram(x =  ageArray[jobArray == 'NO'],
              name = "Disoccupato",
              histnorm='probability',
              marker = dict(color = 'rgb(0,0,255)')       
             ) 
 

layout = go.Layout(title = 'Histogramma normalizzato: Distribuzione delle età', xaxis = dict(title ='età'), yaxis = dict(title = 'Frequenze relative'))

groupBox = go.Figure(data = [hist1,  hist2], layout = layout)

py.iplot(groupBox)

### 2.4 (opzionale)
Ripetere l'analisi bivariata dell'esercizio utilizzando un'altra variabile categorica e/o un'altra variabile numerica. Ad esempio, potete studiare la relazione tra età degli utenti e reddito (dividendo il reddito in 3 gruppi). Hint: se guardate i redditi dichiarati compare spesso '-1', che equivale al campo non compilato dall'utente (vedi cella sotto). Se volete fare un'analisi dei redditi, rimuovete questi utenti nella vostra analisi come mostrato nella cella sotto.

In [20]:
# Hint
print(df['income'].values)

maskIndex = df['income'].values != -1 
arrayIncome = df['income'].values[maskIndex]
arrayAgeNew = df['age'].values[maskIndex] 

[    -1  80000     -1 ... 100000     -1     -1]


## Esercizio 3
Si consideri il dataset [Numbeo](https://www.numbeo.com/cost-of-living/), che fornisce informazioni e indici per misurare le condizioni di vita nei vari Paesi del mondo (misurate in termini di costo della vita, tasso di criminalità, inquinamento, traffico, etc.).

Eseguiamo la cella sotto e importiamo con pandas la [tabella](https://www.numbeo.com/quality-of-life/rankings_by_country.jsp) che riporta i principali indicatori per misurare la qualità della vita in un Paese, e concentriamoci sui due attributi **costo della vita** (``Cost of Living Index`` nella tabella) e **tasso di inquinamento** (``Pollution Index`` nella tabella).

In [21]:
# Da eseguire per importare i dati

# Create pandas dataframe
dfLife = pd.read_html('https://www.numbeo.com/quality-of-life/rankings_by_country.jsp')
dfLife = dfLife[2] 

# Select attributes Country, Cost of Living Index, and Pollution Index

arrayCountry = dfLife['Country'].values            # Nomi dei Paesi
arrayCost = dfLife['Cost of Living Index'].values
arrayPollution = dfLife['Pollution Index'].values

### 3.1
Disegnare lo scatterplot tra le variabili **costo della vita** e **tasso di inquinamento**. Guardando il grafico appena generato, le due variabili sono tra loro correlate? Sempre guardando il grafico, sapete già dire se il coefficiente di correlazione sarà positivo, negativo, o circa nullo?  

In [22]:
# Hint per generare uno scatter plot

xData = np.random.rand(1000)
yData = 2*xData + 0.3*np.random.randn(1000)

trace = go.Scatter(x = xData, y = yData,  
                   mode = 'markers', 
                   marker = {'color': 'rgb(255,0,0)', 'size': 5, 'symbol': 'circle', 'opacity': 0.5}) 

layout = go.Layout( title = 'Scatterplot (x vs y)',
                    xaxis = {'title': 'x'},
                    yaxis = {'title': 'y'})
fig = go.Figure(data = [trace], layout = layout)
py.iplot(fig)

In [23]:
# Solution

trace = go.Scatter(x = dfLife['Cost of Living Index'].values, y = dfLife['Pollution Index'].values,  
                   mode = 'markers', 
                   marker = {'color': 'rgb(255,0,0)', 'size': 5, 'symbol': 'circle', 'opacity': 0.5}) 

layout = go.Layout( title = 'Costo della vita vs Tasso di inquinamento nei diversi Stati',
                    xaxis = {'title': 'Costo della vita'},
                    yaxis = {'title': 'Tasso di inquinamento'})
fig = go.Figure(data = [trace], layout = layout)
py.iplot(fig)

print("Le variabili sono correlate con coefficiente di correlazione negativo: Al diminuire del tasso di inquinamento, il costa della vita aumenta")

Le variabili sono correlate con coefficiente di correlazione negativo: Al diminuire del tasso di inquinamento, il costa della vita aumenta


### 3.2 
Calcolare il coefficiente di correlazione tra le variabili *costo della vita* e *tasso di inquinamento*.

In [24]:
# Hint
# Per calcolare la matrice di correlazione tra le varianili 'a' e 'b'

a = np.array([2,4,5,8])
b = - np.array([2,6,1,9])

coeff = np.corrcoef([a,b])
print(coeff)

[[ 1.         -0.70330232]
 [-0.70330232  1.        ]]


In [25]:
# Solution

corrcoef = np.corrcoef([dfLife['Cost of Living Index'].values, dfLife['Pollution Index'].values])

print(f"Matrice di correlazione:\n {corrcoef}")

Matrice di correlazione:
 [[ 1.        -0.6584181]
 [-0.6584181  1.       ]]


### 3.3 (opzionale, per ripassare l'analisi univariata)
Disegnare l'istogramma e il boxplot della variabile **indice sulla qualità delle vita** (colonna ``Quality of Life Index`` del dataframe importato prima). Calcolare media, mediana, varianza, e deviazione standard, primo e terzo quartile, 90-esimo percentile. E' giusto dire (secondo i dati di Numbeo) che la Svizzera è tra il 10% dei paesi con l'indice di qualità della vita piu' alto?

In [26]:
# Solution
arrayQuality = dfLife['Quality of Life Index'].values

trace = go.Box(x = arrayQuality)
layout = go.Layout(title = 'Distribuzione indice qualità della vita per diversi Paesi del mondo',
                   xaxis = dict(title = 'Indice su qualità della vita'))
box = go.Figure(data = [trace], layout = layout)
py.iplot(box)

trace = go.Histogram(x = arrayQuality, nbinsx = 25)
layout2 = go.Layout(title = 'Distribuzione indice qualità della vita per diversi Paesi del mondo',
                   xaxis = dict(title = 'Indice su qualità della vita'),
                   yaxis = dict(title = 'Numero di Paesi'))
histogram = go.Figure(data = [trace], layout = layout2)
py.iplot(histogram)


indiceSvizzera = (arrayCountry == 'Switzerland')

# Se arrayQuality[indiceSvizzera] > 90-esimo percentile, allora la Svizzera è tra il 10% percento dei paesi con piu' alta qualita della vita

if arrayQuality[indiceSvizzera] > np.percentile(arrayQuality,90):
    print("La Svizzera è tra il 10%  dei paesi con la piu' alta qualità della vita")
else:
    print("La Svizzera NON è tra il 10%  dei paesi con la piu' alta qualità della vita")

La Svizzera è tra il 10%  dei paesi con la piu' alta qualità della vita
