# Blah blah
## blah blah
### blah

In [51]:
import numpy as np

array_1 = np.array([0,1,2,3])
array_2 = np.array([9,8,7])
array_1[1:] = array_2
array_1[2] = 333
print(array_1)
print(array_2)
#array_2[[True, False, True, True]]#Non ha senso da fare perché non è della stessa dimensione

#Questo si può fare invece perché python è una merda incosisnte
#senza un buon approccio versolo il buon senso e la logica
array_2[[0,2,1,2,0,1,2,1,2,0,0,0]]



[  0   9 333   7]
[9 8 7]
[0 0 0 1]
[0 1 1 1]


In [72]:
array_p = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13])
print((array_p % 2))
print((array_p % 3))
print((array_p % 5))
a = (array_p % 2)
a[2] = 2
for i in range(1):
    print(i)

[1 0 1 0 1 0 1 0 1 0 1 0 1]
[1 2 0 1 2 0 1 2 0 1 2 0 1]
[1 2 3 4 0 1 2 3 4 0 1 2 3]
0
